// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://shfleoigdsgvmdfijaqi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNoZmxlb2lnZHNndm1kZmlqYXFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAwNDE2MjYsImV4cCI6MjA1NTYxNzYyNn0.h8TlGJ3enHOX38sj4gnQGX0duKx7OxBfXkjpkm-T7aw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);